name: Surface

on:
  pull_request:
  push:
    branches:
      - master
    paths-ignore:
      - '.git-crypt/**'
      - '.gitattributes'
      - '.gitignore'
      - 'user/**'
      - 'system/nixos/**'
      - 'bin/**'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    
    - name: "Install Nix"
      uses: cachix/install-nix-action@v16
        
    - name: "Install Cachix"
      uses: cachix/cachix-action@v10
      with:
        name: tnargy
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        
    - name: "Build Surface"
      run: nix build .#nixosConfigurations.surface.config.system.build.toplevel
