name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    
    - name: "Install Nix"
    - uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        
    - name: "Install Cachix"
    - uses: cachix/cachix-action@v10
      with:
        name: tnargy
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        
    - name: "Build Home Manager config"
    - run: nix build .#homeConfigurations.onyx.activationPackage
